### ISSUE TITLE
Problem with latest version and Home Assistant 14

### ISSUE THREAD

**Issue by MHx489** [sunfounder/pironman5#17]
Hi, after Update to Home Assistant 14, Pironman 5 with latest Addon version won't startup. Following Log Errors

Traceback (most recent call last):
File "/opt/pironman5/venv/bin/pironman5-service", line 8, in
sys.exit(main())
^^^^^^
File "/opt/pironman5/venv/lib/python3.12/site-packages/pironman5/init.py", line 8, in main
from .pironman5 import Pironman5
File "/opt/pironman5/venv/lib/python3.12/site-packages/pironman5/pironman5.py", line 40, in
if get_hat_version() < 11:
^^^^^^^^^^^^^^^^^
File "/opt/pironman5/venv/lib/python3.12/site-packages/pironman5/utils.py", line 37, in get_hat_version
with open(f"{hat_path}/product_ver", "r") as f:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'None/product_ver'

**Comment by cavonlee** [comment]
Fix, try update your addon in Home assistant
